service: serverless-dynamodb

plugins: 
  - serverless-offline
  - serverless-dynamodb-local

  package: 
    individually: true

  custom:
    tableName: test-table
    bucketName: test-bucket
    dynamodb:
      stages:
        - dev
      start:
        port: 8000
        inMemory: true
        migrate: true
      migration:
        dir: offline/migrations

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  enviroment:
    tableName: ${self:custom.tableName}
    bucketName: ${self:custom.bucketName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
        - ses:*
      Resources: '*'
functions:
  app:
    handler: index.handler
    events:
      - http: 
          path: /dev
          method: GET